# Site settings
title: Amy Laun
email: amylaun@gmail.com
description: > # My name is Amy. I am a lover of laughing, hammocks, and pie.
baseurl: ""
logo: ""
url: "http://amylaun.com"
url_img: "/assets/images"
twitter_username: amypotato
github_username:  amylaun
insta_username:  dandetiger

# Build settings
markdown: kramdown
exclude: ['node_modules', 'css', '_scss']
keep_files: ['_site/css']

# Site Collections
collections:
  projects:
    output: true
    permalink: '/:collection/:title/'
